<?php
class A{
    static function sayHi(){
        echo "Hi From a\n";
    }
}
class B extends A{
    static function sayHi()
    {
        echo "hi from B\n";
        parent::sayHi(); // TODO: Change the autogenerated stub
    }
}
B::sayHi();